Algoritmo "CAMISA-CR7"

Var
// Seção de Declarações das variáveis 
numeroCamisa: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

enquanto numeroCamisa <> 7 faca
         Escreva("Qual o número da camisa de Cristiano Ronaldo? ")
         Leia(numeroCamisa)
         Se(numeroCamisa <>7) entao
                         Escreval("Ops!, tente novamente")
         Fimse
Fimenquanto

           Escreval("Parabens, você acertou! SIRRRRR!")

Fimalgoritmo