Algoritmo "FUNCAO-SOMAR"

Var
// Seção de Declarações das variáveis 
numero1, numero2: Inteiro

funcao somar(num1, num2: inteiro):inteiro
       var
       Inicio
             retorne num1 + num2
fimfuncao

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o primeiro número:")
Leia(numero1)
Escreva("Digite o segundo número:")
Leia(numero2)

Escreval("Resultado da soma:", somar(numero1, numero2))

Fimalgoritmo