Algoritmo "IDADE-3-PESSOAS"

Var
// Seção de Declarações das variáveis 
count, idade: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para count de 1 ate 3 faca
     Escreva("Informe a sua idade: ")
     Leia(idade)
     
                Se(idade >= 18) entao
                Escreval("Você é maior de idade!")
     senao
          Escreval("Você não é maior de idade!")
          
     Fimse
Fimpara

Fimalgoritmo